// this is just a placeholder list of countries.

// TODO: this should be replaced by list of countries fetch from a CDN
export const countries = [
  { label: 'Estonia', value: 'Estonia' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Nigeria', value: 'Nigeria' },
  { label: 'United Kingdom', value: 'United Kingdom' },
  { label: 'United States', value: 'United States' },
  { label: 'Ghana', value: 'Ghana' },
  { label: 'South Africa', value: 'South Africa' },
  { label: 'Kenya', value: 'Kenya' },
  { label: 'Uganda', value: 'Uganda' },
  { label: 'Tanzania', value: 'Tanzania' },
  { label: 'Zambia', value: 'Zambia' },
  { label: 'Zimbabwe', value: 'Zimbabwe' },
  { label: 'Malawi', value: 'Malawi' },
  { label: 'Mozambique', value: 'Mozambique' },
  { label: 'Angola', value: 'Angola' },
  { label: 'Namibia', value: 'Namibia' },
  { label: 'Botswana', value: 'Botswana' },
  { label: 'Swaziland', value: 'Swaziland' },
  { label: 'Lesotho', value: 'Lesotho' },
  { label: 'Mauritius', value: 'Mauritius' },
  { label: 'Seychelles', value: 'Seychelles' },
  { label: 'Comoros', value: 'Comoros' },
  { label: 'Madagascar', value: 'Madagascar' },
  { label: 'Mauritania', value: 'Mauritania' },
  { label: 'Senegal', value: 'Senegal' },
  { label: 'Gambia', value: 'Gambia' },
  { label: 'Guinea-Bissau', value: 'Guinea-Bissau' },
  { label: 'Guinea', value: 'Guinea' },
  { label: 'Sierra Leone', value: 'Sierra Leone' },
  { label: 'Liberia', value: 'Liberia' },
  { label: 'Burkina Faso', value: 'Burkina Faso' },
  { label: 'Togo', value: 'Togo' },
  { label: 'Benin', value: 'Benin' },
  { label: 'Niger', value: 'Niger' },
  { label: 'Mali', value: 'Mali' },
  { label: 'Algeria', value: 'Alger' },
  { label: 'France', value: 'France' },
  { label: 'Germany', value: 'Germany' },
  { label: 'Spain', value: 'Spain' },
  { label: 'Italy', value: 'Italy' },
  { label: 'Netherlands', value: 'Netherlands' },
  { label: 'Belgium', value: 'Belgium' },
  { label: 'Switzerland', value: 'Switzerland' },
  { label: 'Austria', value: 'Austria' },
  { label: 'Sweden', value: 'Sweden' },
  { label: 'Norway', value: 'Norway' },
  { label: 'Denmark', value: 'Denmark' },
  { label: 'Finland', value: 'Finland' },
  { label: 'Poland', value: 'Poland' },
  { label: 'Czech Republic', value: 'Czech Republic' },
  { label: 'Hungary', value: 'Hungary' },
  { label: 'Romania', value: 'Romania' },
  { label: 'Bulgaria', value: 'Bulgaria' },
  { label: 'Greece', value: 'Greece' },
  { label: 'Portugal', value: 'Portugal' },
  { label: 'Ireland', value: 'Ireland' },
  { label: 'Croatia', value: 'Croatia' },
  { label: 'Slovakia', value: 'Slovakia' },
  { label: 'Slovenia', value: 'Slovenia' },
  { label: 'Estonia', value: 'Estonia' },
  { label: 'Latvia', value: 'Latvia' },
  { label: 'Lithuania', value: 'Lithuania' },
  { label: 'Luxembourg', value: 'Luxembourg' },
  { label: 'Malta', value: 'Malta' },
  { label: 'Cyprus', value: 'Cyprus' },
  { label: 'Canada', value: 'Canada' },
  { label: 'Mexico', value: 'Mexico' },
  { label: 'Belize', value: 'Belize' },
  { label: 'Costa Rica', value: 'Costa Rica' },
  { label: 'El Salvador', value: 'El Salvador' },
  { label: 'Guatemala', value: 'Guatemala' },
  { label: 'Honduras', value: 'Honduras' },
  { label: 'Nicaragua', value: 'Nicaragua' },
  { label: 'Panama', value: 'Panama' },
  { label: 'Bahamas', value: 'Bahamas' },
  { label: 'Barbados', value: 'Barbados' },
  { label: 'Dominica', value: 'Dominica' },
  { label: 'Dominican Republic', value: 'Dominican Republic' },
  { label: 'Grenada', value: 'Grenada' },
  { label: 'Haiti', value: 'Haiti' },
  { label: 'Jamaica', value: 'Jamaica' },
  { label: 'Saint Kitts and Nevis', value: 'Saint Kitts and Nevis' },
  { label: 'Saint Lucia', value: 'Saint Lucia' },
  {
    label: 'Saint Vincent and the Grenadines',
    value: 'Saint Vincent and the Grenadines',
  },
  { label: 'Trinidad and Tobago', value: 'Trinidad and Tobago' },
  { label: 'Argentina', value: 'Argentina' },
  { label: 'Bolivia', value: 'Bolivia' },
  { label: 'Brazil', value: 'Brazil' },
  { label: 'Chile', value: 'Chile' },
  { label: 'Colombia', value: 'Colombia' },
  { label: 'Ecuador', value: 'Ecuador' },
  { label: 'Guyana', value: 'Guyana' },
  { label: 'Paraguay', value: 'Paraguay' },
  { label: 'Peru', value: 'Peru' },
  { label: 'Suriname', value: 'Suriname' },
  { label: 'Uruguay', value: 'Uruguay' },
  { label: 'Venezuela', value: 'Venezuela' },
];
